/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
Title: Tenhun Falling spaceman (FanArt)
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";

function MillenniumFalconSpaceship(props) {
  const group = useRef();
  const bulletsRef = useRef(new Array(16).fill(null));
  
  // Realistic flying animation - same as main model
  useFrame((state) => {
    if (group.current) {
      // Realistic flying motion - positioned in middle
      const time = state.clock.elapsedTime;
      
      // Complex left-right movement with varying speed
      group.current.position.x = 1.3 + 
        Math.sin(time * 0.7) * 0.4 + 
        Math.sin(time * 1.3) * 0.15;
      
      // Vertical hovering in middle of screen
      group.current.position.y = 0.2 + 
        Math.sin(time * 0.5) * 0.25 + 
        Math.cos(time * 0.9) * 0.1;
      
      // Realistic banking and pitch movements
      group.current.rotation.z = Math.sin(time * 0.6) * 0.08 + Math.cos(time * 1.1) * 0.03;
      group.current.rotation.x = Math.sin(time * 0.4) * 0.04;
      group.current.rotation.y = Math.sin(time * 0.3) * 0.06;
      
      // Animate bullets
      bulletsRef.current.forEach((bullet, index) => {
        if (bullet) {
          bullet.position.z += 0.4;
          bullet.position.y += Math.sin(state.clock.elapsedTime * 3 + index) * 0.03;
          
          if (bullet.position.z > 8) {
            bullet.position.z = -1 - (index % 8) * 0.3;
            bullet.position.x = Math.random() * 0.6 - 0.3;
            bullet.position.y = Math.random() * 0.3 - 0.15;
          }
        }
      });
    }
  });

  return (
    <group
      ref={group}
      {...props}
      scale={props.scale || 0.5}
      position={props.position || [1.3, 0.2, 0]}
    >
      {/* Add lighting for better visibility */}
      <ambientLight intensity={0.8} />
      <directionalLight position={[5, 5, 5]} intensity={1.0} />
      <pointLight position={[2, 2, 2]} intensity={0.8} color="#ffffff" />
      
      {/* Main body - Millennium Falcon style */}
      <mesh rotation={[0, 0, Math.PI / 2]}>
        <cylinderGeometry args={[0.8, 1.2, 0.4, 6]} />
        <meshBasicMaterial color="#F0F0F0" />
      </mesh>
      
      {/* Central disc */}
      <mesh>
        <cylinderGeometry args={[0.6, 0.6, 0.2, 16]} />
        <meshBasicMaterial color="#FFFFFF" />
      </mesh>
      
      {/* Cockpit - offset to the right like Millennium Falcon */}
      <mesh position={[0.8, 0.15, 0]}>
        <sphereGeometry args={[0.3]} />
        <meshBasicMaterial color="#D0D0D0" />
      </mesh>
      
      {/* Cockpit window */}
      <mesh position={[0.9, 0.2, 0]}>
        <sphereGeometry args={[0.15]} />
        <meshBasicMaterial color="#87CEEB" />
      </mesh>
      
      {/* Forward mandibles - characteristic Millennium Falcon shape */}
      <mesh position={[-0.6, 0, 0.6]} rotation={[0, 0, 0.2]}>
        <boxGeometry args={[1.2, 0.3, 0.25]} />
        <meshBasicMaterial color="#F0F0F0" />
      </mesh>
      <mesh position={[-0.6, 0, -0.6]} rotation={[0, 0, -0.2]}>
        <boxGeometry args={[1.2, 0.3, 0.25]} />
        <meshBasicMaterial color="#F0F0F0" />
      </mesh>
      
      {/* Mandible tips */}
      <mesh position={[-1.1, 0, 0.7]}>
        <boxGeometry args={[0.3, 0.2, 0.15]} />
        <meshBasicMaterial color="#E0E0E0" />
      </mesh>
      <mesh position={[-1.1, 0, -0.7]}>
        <boxGeometry args={[0.3, 0.2, 0.15]} />
        <meshBasicMaterial color="#E0E0E0" />
      </mesh>
      
      {/* Rear engines */}
      <mesh position={[0.8, 0, 0]}>
        <cylinderGeometry args={[0.1, 0.15, 0.4]} />
        <meshBasicMaterial color="#4169E1" />
      </mesh>
      
      {/* Engine glow effects */}
      <mesh position={[1.0, 0, 0]}>
        <cylinderGeometry args={[0.05, 0.1, 0.2]} />
        <meshBasicMaterial color="#00BFFF" />
      </mesh>
      
      {/* Add some detail lines in gray */}
      <mesh position={[0, 0, 0]}>
        <torusGeometry args={[0.9, 0.02, 8, 16]} />
        <meshBasicMaterial color="#CCCCCC" />
      </mesh>
      
      {/* Red laser bullets for fallback */}
      {[...Array(6)].map((_, i) => (
        <mesh
          key={i}
          ref={(el) => (bulletsRef.current[i] = el)}
          position={[
            Math.random() * 0.4 - 0.2,
            Math.random() * 0.2 - 0.1,
            -2 - i * 0.5
          ]}
        >
          <cylinderGeometry args={[0.02, 0.02, 0.2]} />
          <meshBasicMaterial color="#FF0000" />
        </mesh>
      ))}
    </group>
  );
}

export function Astronaut(props) {
  return <MillenniumFalconSpaceship {...props} />;
}
